version: '2.1'
services:
  zookeeper:
    image: zookeeper:3.3.6
    ports:
    - 2181:2181
    environment:
      ZOO_STANDALONE_ENABLED: "TRUE"
    restart: on-failure

  kafka:
    image: wurstmeister/kafka:1.1.0
    depends_on:
    - zookeeper
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_CREATE_TOPICS: "test:1:1"
    restart: on-failure

#  kage:
#    build: .
#    image: kage:test
#    depends_on:
#      kafka:
#        condition: service_healthy
#    links:
#      - kafka
#    environment:
#      - KAGE_KAFKA_BROKERS=kafka:9092
#  kafka:
#    image: 'spotify/kafka:latest'
#    environment:
#      - ADVERTISED_PORT=9092
#    logging:
#      driver: "none"
#    healthcheck:
#      test: bash -c "cat < /dev/null > /dev/tcp/localhost/9092"
#      interval: 10s
#      timeout: 10s
#      retries: 5
#  producer:
#    image: 'spotify/kafka:latest'
#    logging:
#      driver: "none"
#    depends_on:
#      kafka:
#        condition: service_healthy
#    links:
#      - kafka
#    command: sh -c "while /bin/true; do echo PING|$$KAFKA_HOME/bin/kafka-console-producer.sh --broker-list kafka:9092 --topic test; sleep 0.1; done"
#  consumer:
#    image: 'spotify/kafka:latest'
#    logging:
#      driver: "none"
#    depends_on:
#      kafka:
#        condition: service_healthy
#    links:
#      - kafka
#    command: sh -c "$$KAFKA_HOME/bin/kafka-console-consumer.sh --bootstrap-server kafka:9093 --topic test"
