version: '2.1'
services:
  zookeeper:
    image: zookeeper:3.3.6
    ports:
    - 2181:2181
    environment:
      ZOO_STANDALONE_ENABLED: "TRUE"
    restart: on-failure

  kafka:
    image: wurstmeister/kafka:1.1.0
    depends_on:
    - zookeeper
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_CREATE_TOPICS: "test:1:1"
    restart: on-failure
