#!/bin/sh

# we want one symlink per .json in /etc/kage so that we're spawning them all

set -eu

set -eu

GENDIR="$1"
WANTDIR="$1/kage.service.wants"
SERVICEFILE="/lib/systemd/system/kage@.service"
AUTOSTART="all"
CONFIG_DIR=/etc/kage

mkdir -p "$WANTDIR"

if test -e /etc/default/kage ; then
        . /etc/default/kage
fi

if test "x$AUTOSTART" = "xnone" ; then
        exit 0
fi

if test "x$AUTOSTART" = "xall" -o -z "$AUTOSTART" ; then
        for CONFIG in `cd $CONFIG_DIR; ls *.json 2> /dev/null`; do
                NAME=${CONFIG%%.json}
                ln -s "$SERVICEFILE" "$WANTDIR/kage@$NAME.service"
        done
else
        for NAME in $AUTOSTART ; do
                if test -e $CONFIG_DIR/$NAME.json ; then
                        ln -s "$SERVICEFILE" "$WANTDIR/kage@$NAME.service"
                fi
        done
fi

exit 0

